import { Component, OnInit, ViewChild } from '@angular/core';
import SwiperCore, { Keyboard, Lazy, Navigation, Pagination, SwiperOptions } from 'swiper';
import { SwiperComponent } from 'swiper/angular';
SwiperCore.use([Navigation, Keyboard, Lazy, Pagination]);

@Component({
  selector: 'app-cardapio',
  templateUrl: './cardapio.page.html',
  styleUrls: ['./cardapio.page.scss'],
})
export class CardapioPage implements OnInit {
  constructor() { }

  ngOnInit() {
    
  }

  onSwiper(swiper) {
    console.log(swiper);
  }
  onSlideChange(swiper) {
    console.log('slide change');
  }


  config: SwiperOptions = {
    pagination: {
      type: 'fraction'
    },
    freeMode: true,
    direction: "horizontal",
    grabCursor: true,
    keyboard: {
      enabled: true,
      onlyInViewport: true
    },
    initialSlide: 0,
    slidesPerView: 2,
    spaceBetween: 16,
    navigation: true,
    breakpoints: {
      630: {
        slidesPerView: 3,
        freeMode: true,
      },
      800: {
        slidesPerView: 4,
        freeMode: true,
      },
      960: {
        slidesPerView: 5,
        freeMode: true,
      },
      1200: {
        slidesPerView: 6,
        freeMode: true,
      }
    }
  };

  pizzas: {
    text: string,
    imgPath: string,
    description: string,
    linkTamanhoG: string,
    linkTamanhoP: string,
    precoTamanhoG: number,
    precoTamanhoP: number
  }[] = [
    {
      text: 'Banana com chocolate',
      imgPath: 'banana-c-chocolate',
      description: 'Banana, açúcar, canela e chocolate.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=174',
      precoTamanhoP: 35.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=74',
      precoTamanhoG: 45.9,
    },
    {
      text: 'Nevada',
      imgPath: 'nevada',
      description: 'Banana com canela e chocolate branco gratinado.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=182',
      precoTamanhoP: 35.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=82',
      precoTamanhoG: 45.9,
    },
    {
      text: 'Baião',
      imgPath: 'baiao',
      description: 'Mussarela, carne seca, cebola, queijo coalho e pimenta biquinho.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=107',
      precoTamanhoP: 62.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=7',
      precoTamanhoG: 76.9,
    },
    {
      text: 'Natureba',
      imgPath: 'natureba',
      description: 'Mussarela, cream cheese, peito de peru, tomate cereja, alho poró e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=168',
      precoTamanhoP: 58.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=68',
      precoTamanhoG: 76.9,
    },
    {
      text: 'Champeroni',
      imgPath: 'champeroni',
      description: 'Mussarela, champignon rosé e pepperoni.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=127',
      precoTamanhoP: 60.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=27',
      precoTamanhoG: 73.9,
    },
    {
      text: 'Pestinha',
      imgPath: 'pestinha',
      description: 'Manjericão, tomate seco feito na casa, mussarela vegana a base de castanha de caju e pesto de azeitona preta.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=187',
      precoTamanhoP: 63.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=87',
      precoTamanhoG: 79.9,
    },
    {
      text: 'Vrango',
      imgPath: 'vrango',
      description: 'Frango de soja, milho, queijo a base de castanhas, queijo cremoso vegano sabor provolone, e azeitona.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=159',
      precoTamanhoP: 60.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=59',
      precoTamanhoG: 75.9,
    },
    {
      text: 'Portuga Virou Vegan',
      imgPath: 'portuga-virou-vegan',
      description: 'Queijo de castanha, presunto de soja, ervilha, palmito e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=157',
      precoTamanhoP: 58.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=57',
      precoTamanhoG: 78.9,
    },
    {
      text: 'Shimeji',
      imgPath: 'shimeji',
      description: 'Mussarela, shimeji refogado e cebolinha.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=177',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=77',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Tipo oitava',
      imgPath: 'tipo-oitava',
      description: 'Tomate seco feito na casa, manjericão, queijo cremoso vegano sabor provolone, alho poró e alho frito.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=186',
      precoTamanhoP: 62.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=86',
      precoTamanhoG: 78.9,
    },
    {
      text: 'Aquilino',
      imgPath: 'aquilino',
      description: 'Mussarela, lombo e gorgonzola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=160',
      precoTamanhoP: 48.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=60',
      precoTamanhoG: 63.9,
    },
    {
      text: '3 TOMATES',
      imgPath: '3-tomates',
      description: 'Tomate seco feito na casa, provolone, catupiry, tomate sweet grape e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=199',
      precoTamanhoP: 59.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=99',
      precoTamanhoG: 75.9,
    },
    {
      text: 'Quejo coalho',
      imgPath: 'queijo-coalho',
      description: 'Mussarela, queijo coalho e geléia de pimenta (não picante).',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=196',
      precoTamanhoP: 52.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=96',
      precoTamanhoG: 68.9,
    },
    {
      text: 'Cream shi',
      imgPath: 'cream-shi',
      description: 'Mussarela, shimeji e cream cheese.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=194',
      precoTamanhoP: 53.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=94',
      precoTamanhoG: 67.9,
    },
    {
      text: 'Baião Vegetariana',
      imgPath: 'baiao-vegetariana',
      description: 'Mussarela, shimeji, cebola, queijo coalho e pimenta biquinho.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=198',
      precoTamanhoP: 57.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=98',
      precoTamanhoG: 72.9,
    },
    {
      text: 'Naturalis',
      imgPath: 'naturalis',
      description: 'Mussarela, alho poró, abobrinha, cream cheese, tomate sweet grape e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=197',
      precoTamanhoP: 57.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=97',
      precoTamanhoG: 72.9,
    },
    {
      text: 'Churros',
      imgPath: 'churros',
      description: 'Doce de leite, açúcar e canela.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=180',
      precoTamanhoP: 35.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=80',
      precoTamanhoG: 45.9,
    },
    {
      text: 'Calagorgon',
      imgPath: 'calagorgon',
      description: 'Calabresa, cebola roxa, gorgonzola, cream cheese e azeitona preta.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=178',
      precoTamanhoP: 52.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=78',
      precoTamanhoG: 72.9,
    },
    {
      text: 'Frango stein',
      imgPath: 'frango-stein',
      description: 'Frango, catupiry, mussarela, gorgonzola parmesão e azeitonas pretas.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=117',
      precoTamanhoP: 55.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=17',
      precoTamanhoG: 72.9,
    },
    {
      text: 'Peppeleia',
      imgPath: 'peppeleia',
      description: 'Mussarela, pepperoni e geleia de pimenta (não picante).',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=179',
      precoTamanhoP: 52.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=79',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Abobrinha',
      imgPath: 'abobrinha',
      description: 'Mussarela, alho poró, abobrinha, cream cheese e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=175',
      precoTamanhoP: 46.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=75',
      precoTamanhoG: 59.9,
    },
    {
      text: 'Pizzaiola',
      imgPath: 'pizzaiola',
      description: 'Mussarela, atum, calabresa fatiada, catupiry e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=134',
      precoTamanhoP: 57.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=34',
      precoTamanhoG: 74.9,
    },
    {
      text: 'Mussarela',
      imgPath: 'mussarela',
      description: 'Mussarela e rodelas tomate.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=101',
      precoTamanhoP: 38.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=1',
      precoTamanhoG: 49.9,
    },
    {
      text: 'Marguerita',
      imgPath: 'marguerita',
      description: 'Mussarela, manjericão, tomate e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=104',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=4',
      precoTamanhoG: 52.9,
    },
    {
      text: 'Napolitana',
      imgPath: 'napolitana',
      description: 'Mussarela, parmesão, tomate e alho frito.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=105',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=5',
      precoTamanhoG: 52.9,
    },
    {
      text: 'Catupiry',
      imgPath: 'catupiry',
      description: 'Catupiry, rodelas de tomate e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=103',
      precoTamanhoP: 38.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=3',
      precoTamanhoG: 49.9,
    },
    {
      text: '2 Queijos',
      imgPath: '2-queijos',
      description: 'Mussarela e catupiry.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=106',
      precoTamanhoP: 43.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=6',
      precoTamanhoG: 55.9,
    },
    {
      text: '4 Queijos',
      imgPath: '4-queijos',
      description: 'Mussarela, catupiry, provolone e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=131',
      precoTamanhoP: 47.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=31',
      precoTamanhoG: 60.9,
    },
    {
      text: 'Oitava',
      imgPath: 'oitava',
      description: 'Mussarela, gorgonzola, manjericão, tomate seco e alho frito.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=161',
      precoTamanhoP: 58.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=61',
      precoTamanhoG: 75.9,
    },
    {
      text: '5 Queijos',
      imgPath: '5-queijos',
      description: 'Mussarela, catupiry, gorgonzola, provolone e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=136',
      precoTamanhoP: 51.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=36',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Rúcula',
      imgPath: 'rucula',
      description: 'Tomate seco, mussarela e rúcula enviada a parte.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=158',
      precoTamanhoP: 50.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=58',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Tomate seco especial',
      imgPath: 'tomate-seco-especial',
      description: 'Tomate seco, mussarela, alho poró e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=170',
      precoTamanhoP: 52.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=70',
      precoTamanhoG: 68.9,
    },
    {
      text: 'Champignon',
      imgPath: 'champignon',
      description: 'Mussarela e champignon ao molho rosé.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=124',
      precoTamanhoP: 50.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=24',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Pepperoni',
      imgPath: 'pepperoni',
      description: 'Mussarela e pepperoni.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=141',
      precoTamanhoP: 51.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=41',
      precoTamanhoG: 62.9,
    },
    {
      text: 'Siciliana',
      imgPath: 'siciliana',
      description: 'Mussarela, champignon souté e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=125',
      precoTamanhoP: 45.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=25',
      precoTamanhoG: 58.9,
    },
    {
      text: 'Bolonha',
      imgPath: 'bolonha',
      description: 'Mussarela, presunto, tomate, champignon ao molho souté e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=145',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=45',
      precoTamanhoG: 63.9,
    },
    {
      text: 'Palmito',
      imgPath: 'palmito',
      description: 'Mussarela e palmito.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=152',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=52',
      precoTamanhoG: 63.9,
    },
    {
      text: 'Palmitoró',
      imgPath: 'palmitoro',
      description: 'Palmito, alho poró, mussarela e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=167',
      precoTamanhoP: 54.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=67',
      precoTamanhoG: 69.9,
    },
    {
      text: 'Simone',
      imgPath: 'simone',
      description: 'Brócolis, palmito, alho poró, tomate e mussarela.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=163',
      precoTamanhoP: 51.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=63',
      precoTamanhoG: 66.9,
    },
    {
      text: 'Brócolis',
      imgPath: 'brocolis',
      description: 'Brócolis, mussarela e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=121',
      precoTamanhoP: 45.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=21',
      precoTamanhoG: 56.9,
    },
    {
      text: 'Quebra-mar',
      imgPath: 'quebra-mar',
      description: 'Brócolis, tomate seco feito na casa, mussarela e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=166',
      precoTamanhoP: 53.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=66',
      precoTamanhoG: 68.9,
    },
    {
      text: 'Toscana',
      imgPath: 'toscana',
      description: 'Mussarela, calabresa moída e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=110',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=10',
      precoTamanhoG: 52.9,
    },
    {
      text: 'Paulista',
      imgPath: 'paulista',
      description: 'Mussarela, calabresa fatiada e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=109',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=9',
      precoTamanhoG: 52.9,
    },
    {
      text: 'Moda da casa',
      imgPath: 'moda-da-casa',
      description: 'Mussarela, calabresa moída, catupiry e parmesão.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=122',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=22',
      precoTamanhoG: 65.9,
    },
    {
      text: 'Edu',
      imgPath: 'edu',
      description: 'Brócolis, catupiry, calabresa moída e batata palha.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=135',
      precoTamanhoP: 51.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=35',
      precoTamanhoG: 66.9,
    },
    {
      text: 'Moda do chefe',
      imgPath: 'moda-do-chefe',
      description: 'Mussarela, presunto, ervilha, calabresa e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=123',
      precoTamanhoP: 45.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=23',
      precoTamanhoG: 57.9,
    },
    {
      text: 'Portuguesa',
      imgPath: 'portuguesa',
      description: 'Mussarela, presunto, ervilha, ovo, palmito e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=140',
      precoTamanhoP: 55.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=40',
      precoTamanhoG: 69.9,
    },
    {
      text: 'Atum',
      imgPath: 'atum',
      description: 'Mussarela, atum sólido e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=116',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=16',
      precoTamanhoG: 64.9,
    },
    {
      text: 'Capri',
      imgPath: 'capri',
      description: 'Mussarela, atum, palmito e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=132',
      precoTamanhoP: 57.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=32',
      precoTamanhoG: 74.9,
    },
    {
      text: 'Lombo',
      imgPath: 'lombo',
      description: 'Mussarela, lombo e cebola.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=130',
      precoTamanhoP: 45.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=30',
      precoTamanhoG: 58.9,
    },
    {
      text: 'Frango',
      imgPath: 'frango',
      description: 'Frango desfiado e catupiry.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=115',
      precoTamanhoP: 43.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=15',
      precoTamanhoG: 55.9,
    },
    {
      text: 'Matheus',
      imgPath: 'matheus',
      description: 'Frango desfiado, catupiry e cheddar.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=129',
      precoTamanhoP: 47.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=29',
      precoTamanhoG: 59.9,
    },
    {
      text: 'Caipira',
      imgPath: 'caipira',
      description: 'Frango desfiado, milho, tomate, catupiry e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=128',
      precoTamanhoP: 47.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=28',
      precoTamanhoG: 61.9,
    },
    {
      text: 'Big',
      imgPath: 'big',
      description: 'Frango desfiado, catupiry e champignon ao molho rosé.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=144',
      precoTamanhoP: 57.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=44',
      precoTamanhoG: 73.9,
    },
    {
      text: 'Carne seca',
      imgPath: 'carne-seca',
      description: 'Carne seca, cebola e mussarela.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=142',
      precoTamanhoP: 50.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=42',
      precoTamanhoG: 63.9,
    },
    {
      text: 'Milho',
      imgPath: 'milho',
      description: 'Mussarela, milho e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=108',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=8',
      precoTamanhoG: 50.9,
    },
    {
      text: 'Americana',
      imgPath: 'americana',
      description: 'Mussarela e bacon.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=112',
      precoTamanhoP: 40.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=12',
      precoTamanhoG: 52.9,
    },
    {
      text: 'Eclipse',
      imgPath: 'eclipse',
      description: 'Chocolate branco, cream cheese e Negresco.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=173',
      precoTamanhoP: 41.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=73',
      precoTamanhoG: 51.9,
    },
    {
      text: 'Brigadeiro',
      imgPath: 'brigadeiro',
      description: 'Brigadeiro de panela e chocolate granulado.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=153',
      precoTamanhoP: 45.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=53',
      precoTamanhoG: 45.9,
    },
    {
      text: 'Marverita',
      imgPath: 'marverita',
      description: 'Queijo a base de castanha de caju, manjericão, tomate sweet grape e parmesão vegano a base de castanha de caju.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=181',
      precoTamanhoP: 49.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=81',
      precoTamanhoG: 72.9,
    },
    {
      text: 'Uai Tassio',
      imgPath: 'uai-tassio',
      description: 'Tomate seco, palmito, uai tofu, cebola roxa e queijo a base de castanha de caju.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=184',
      precoTamanhoP: 60.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=84',
      precoTamanhoG: 77.9,
    },
    {
      text: 'The Boinas',
      imgPath: 'the-boinas',
      description: 'Creme de chocolate com avelã vegano.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=189',
      precoTamanhoP: 46.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=89',
      precoTamanhoG: 57.9,
    },
    {
      text: 'Simone Virou Veggie',
      imgPath: 'simone-virou-veggie',
      description: 'Brócolis, tomate seco, provolone requesoy, alho poro, palmito, queijo a base de castanha de caju, orégano e azeitona verde.',
      linkTamanhoP: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=185',
      precoTamanhoP: 60.9,
      linkTamanhoG: 'https://xmenu.com.br/pedidos/?loja=15275&codigo=85',
      precoTamanhoG: 73.9,
    },
  ]
  
}